name: main

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: pip install poetry==1.7.0
      - name: Poetry install
        run: poetry install
      - name: Check formatting
        run: poetry run black --check .
      - name: Run tests
        run: |
          poetry run pytest tests
